### ISSUE TITLE
GitHub actions build failure: `small method list`

### ISSUE THREAD

**Issue by danramteke** [johnxnguyen/Down#238]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?
I am using this project in a static site generator. For my project, `swift test` on macOS locally works, `swift test` on GitHub Actions `ubuntu-latest` works. But not on GitHub Actions `macos-latest`. Any advice?

## What did you expect to happen?

I expected `Down` to compile fine, just like on local macOS, and on GitHub actions `ubuntu-latest`

## What happened instead?

Error during `swift test`
```
objc[4135]: CLASS: class 'Down.DownLayoutManager' 0x112f08f08 small method list 0x112e31e40 is not in immutable memory
```

https://github.com/danramteke/leaf-press/runs/1547255760?check_suite_focus=true
<img width="745" alt="Screen Shot 2020-12-13 at 7 30 21 PM" src="https://user-images.githubusercontent.com/15749/102028740-a5fb9e80-3d79-11eb-93ed-03cee242ab81.png">

**Comment by iwasrobbed** [comment]
I personally don't have any experience w/ GitHub Actions, but typically on other CI systems it's best to SSH into the machine and figure things out locally, then apply the patch and push again.

Here's a related article: https://dev.to/retyui/how-debugging-github-actions-with-ssh-273n?a=github_community

**Comment by danramteke** [comment]
just resolved this by changing my `Package.swift`

i had   ` .macOS(.v11),`
and changed it to   ` .macOS("10.15.4"),`

now it works. thanks so much!
