### ISSUE TITLE
【LaTeX】Hello, I would like to ask how to support LaTeX display in markdown?

### ISSUE THREAD

**Issue by a334713698** [johnxnguyen/Down#241]

**Comment by johnxnguyen** [comment]
Hi @a334713698 , could you please describe what you would like to do? Do you want to input LaTeX and render it using Down?

**Comment by a334713698** [comment]
It's great that you can reply to my question! My requirement is very simple. There are mathematical expressions labeled'$' or'$$' in my markdown string. I want to be able to render and display these markdown strings with mathematical expressions directly through DownView. As shown in the attached picture:
<img width="1553" alt="pic" src="https://user-images.githubusercontent.com/18247575/104877685-553d1e00-5995-11eb-9c65-6bcf28a086ae.png">

**Comment by johnxnguyen** [comment]
@a334713698 no problem, I'm happy to help where I can. Down only supports parsing markdown input according to the CommonMark specification (this is what the cmark library does, which Down uses). Unfortunately this means that LaTeX (including mathematical expressions) can't be rendered in Down.

**Comment by a334713698** [comment]
Okay, I will find other ways to solve my problem. However, Down is still a good program(*￣︶￣)

**Comment by johnxnguyen** [comment]
@a334713698 thanks, and good luck!

**Comment by max-lfeng** [comment]
> Down



> Okay, I will find other ways to solve my problem. However, Down is still a good program(*￣︶￣)

hi，I meet the problem too,  having any solution to display mathematical expressions?
