### ISSUE TITLE
Does not build in 12.5

### ISSUE THREAD

**Issue by codeslubber** [johnxnguyen/Down#244]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Simply attempted to build a project with Down inside that builds in 12.4.

## What did you expect to happen?

That it would build.

## What happened instead?

Crashed with the same error found on this issue:

https://github.com/johnxnguyen/Down/issues/209

**Comment by johnxnguyen** [comment]
Hi @codeslubber , thanks for the report. This is fixed with https://github.com/johnxnguyen/Down/pull/245 and available in `v0.9.5`.
