### ISSUE TITLE
It'd be perfect if there's a example with SwiftUI.

### ISSUE THREAD

**Issue by metrue** [johnxnguyen/Down#256]
Please help prevent duplicate requests before submitting a new one:

* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

## Is your feature request related to a problem? Please describe.

ℹ A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  

## Describe the solution you'd like

ℹ A clear and concise description of what you want to happen.

## Describe alternatives you've considered

ℹ A clear and concise description of any alternative solutions or features you've considered.

**Comment by MrWoWander** [comment]
I offered my example on working with SwiftUI in #260
